---
name: "GitHub Pages"

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  deploy:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Clone the repo"
        uses: "actions/checkout@v4"
        with:
          submodules: true
          fetch-depth: 0

      - name: "Setup Hugo"
        uses: "peaceiris/actions-hugo@v3"
        with:
          hugo-version: 'latest'
          extended: true

      - name: "Build the site"
        run: "hugo --minify"

      - name: "Deploy to GitHub Pages"
        uses: "peaceiris/actions-gh-pages@v3"
        if: "github.ref == 'refs/heads/main'"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "./public"
...
